name: Test Code
on: push
jobs:
    test-code:
        runs-on: ubuntu-latest
        steps:
        - name: Get Code
          uses: actions/checkout@v4.1.1 # This is a GitHub Action that checks out your code. uses = action. checkout = action name. @v4.1.1 = version of the action.
           

